### ISSUE TITLE
Users not visible in DARIAH-DE dashboard

### ISSUE THREAD

**Issue by fungunga** [clarin-eric/monitoring#13]
The users defined in the DARIAH monitoring are not available in the dashboard <https://monitoring.clarin.eu/monitoring/list/contacts>. Is something wrongly configured in the dariah-monitoring?

**Comment by cheapmon** [comment]
The users should be visible now. Please check and give feedback! :slightly_smiling_face:

**Comment by fungunga** [comment]
Something seems to be broken now:

Cannot apply restriction monitoring/filter/objects using the filter hostgroup_name=DARIAH-DE | contactgroup_alias = *DARIAH*. You can only use the following columns: instance_name, host_name, hostgroup_name, service_description, servicegroup_name, _(host|service)_<customvar-name>

I get in dashboard...

**Comment by cheapmon** [comment]
Thanks for the report, the change has been reverted.

**Comment by fungunga** [comment]
Users still are not visible in the Dashboard Contacts menu, and the Contactgroups are visible, but not filled with contacts.

**Comment by jnphilipp** [comment]
As far as I can tell all your contacts are there (https://github.com/clarin-eric/monitoring-dariah/blob/main/users.conf). Bernd is twice.

**Comment by fungunga** [comment]
They are now! Thanks!
