### ISSUE TITLE
deleted entries from centre registry do not result in deletion of checks

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/monitoring#4]
When an entry, like the FCS one for cqlservlet.mpi.nl is removed from the centre registry, the corresponding Icinga check is not removed. Right now this needs to be done manually but it should be possible to automate this.

**Comment by jnphilipp** [comment]
The problem is that at the moment the script doesn't delete conf files if the host hast vanished from centre registry. I'll take a look.

**Comment by jnphilipp** [comment]
The checks for `cqlservlet.mpi.nl` are in https://github.com/clarin-eric/monitoring/blob/3cc7ac40a8d5bfccd24ecc60d74c8e0178d741b5/conf.d/sites/MPI-PL.conf#L22-L29 which is a manual controlled file, which means changes to the centre registry doesn't affect them.

I made some changes to delete host, host groups etc... that are no longer in the centre registry, which for now removes `conf.d/hosts/BenG.conf`and `conf.d/hosts/UIL-OTS.conf`.
