### ISSUE TITLE
False alert for TRTC centre?

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/monitoring#6]
https://monitoring.clarin.eu/monitoring/list/hosts?host_problem=1&sort=host_severity#!/monitoring/host/show?host=TRTC shows a critical alert but works fine for me in a browser for

https://trtc.univie.ac.at/
and
http://trtc.univie.ac.at/

Any idea?

**Comment by jnphilipp** [comment]
This is due to some wired behavior of the http check with http_address set and http_vhost not.
